@host = http://localhost:5000

### Hello world stub
GET {{host}}/hello
Accept: application/json

### Users stub from x-response-file
GET {{host}}/users
Accept: application/json

### Users stub filtered by exact query match
GET {{host}}/users?role=admin
Accept: application/json

### Users stub filtered by another exact query match
GET {{host}}/users?role=guest
Accept: application/json

### Login stub
POST {{host}}/login
Content-Type: application/json
Accept: application/json

{
  "username": "demo",
  "password": "secret"
}

### Unknown route returns 404
GET {{host}}/missing
Accept: application/json
